# agentic-ai-app command surface. `just check` is the quality gate (offline: no provider keys needed).
set dotenv-load := true

default:
    @just --list

setup:
    corepack enable
    pnpm install --frozen-lockfile

# Run the HTTP API with watch (needs a provider key in .env and `just docker-up` for memory)
dev:
    pnpm dev

# Unit + HTTP + MCP tests with mocked models (no network, no Docker)
test *ARGS:
    pnpm test -- {{ARGS}}

# Also run the pgvector memory-store test against the compose database
test-db: docker-up db-migrate
    TEST_DATABASE_URL=${DATABASE_URL} pnpm test -- test/memory-store.test.ts

lint:
    pnpm exec biome check .

fmt:
    pnpm exec biome check --write .

fmt-file FILE:
    pnpm exec biome check --write "{{FILE}}" >/dev/null 2>&1 || true

typecheck:
    pnpm exec tsc --noEmit

build:
    pnpm build

# lint + typecheck + test + build
check: lint typecheck test build
    @echo "check: green"

council BASE="origin/main":
    scripts/council-review.sh {{BASE}}

# Evals against the real agent (needs provider keys; writes evals/output/results.json)
eval: build
    pnpm exec promptfoo eval -c evals/promptfooconfig.yaml --no-cache

# Browse the last eval run
eval-view:
    pnpm exec promptfoo view

# Adversarial prompts generated by promptfoo's red team against the assistant
eval-redteam: build
    pnpm exec promptfoo redteam run -c evals/promptfooconfig.yaml

# Expose the tool registry over MCP (stdio). Register with: claude mcp add ai-app -- just mcp
mcp:
    pnpm mcp

# MCP Inspector against the stdio server
mcp-inspect: build
    npx -y @modelcontextprotocol/inspector@2.5.0 node dist/mcp/server.js

db-generate:
    pnpm db:generate

db-migrate:
    pnpm db:migrate

# pgvector Postgres on host port 5436
docker-up:
    docker compose up -d db

docker-down:
    docker compose down

docker-build:
    docker build -t agentic-ai-app:local .

# Self-hosted Langfuse tracing UI on http://localhost:3001 (set LANGFUSE_* in .env afterwards)
trace-up:
    docker compose --profile trace up -d

trace-down:
    docker compose --profile trace down
